# Generated by Django 4.2.2 on 2023-07-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='composition',
            new_name='types',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='discounted_price',
            new_name='weight',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ps', 'Peste'), ('bh', 'Badoom-Hendi'), ('gr', 'Gerdoo'), ('fn', 'Fandogh'), ('tk', 'Tokhme'), ('bd', 'Bdoom-Derakhti')], max_length=2),
        ),
    ]
